### ISSUE TITLE
[5월 31일~6월6일] 윤형찬 TODO

### ISSUE THREAD

**Issue by hcyspeech** [hcyspeech/Schedule#2]
- 수업 Follow
- [ ] 환경기계공학 과제 (~수)
- [ ] 연구논문 포스터 작성 및 중간 보고 발표 / 연구실 전송 (~수)
- [ ] 기타

(~수)
- 프로젝트 코드 정리
- [ ] GMM based speaker identification
- [ ] Text-independent speaker verification with GE2E loss 
- [ ] Classification of driving sound using spectrogram

(목~토)
- [ ] 전체 프로젝트 복습 
- [ ] PT 발표 피피티 작성 및 연습 (목~)

(일)
- [ ] 음성 합성 공부한 내용들 정리

- 남는 시간
확률과 랜덤 변수, DSP 청강
백준 알고리즘 단계별 풀이: DFS, 백트래킹
